### ISSUE TITLE
 yosys: Use of C++11 final/override keywords breaks build process

### ISSUE THREAD

**Issue by sylv-io** [SymbiFlow/yosys-symbiflow-plugins#22]
Since this change in yosys, it is not possible to build the plugins.

Related upstream issue: https://github.com/YosysHQ/yosys/pull/2173
Related fork merge: https://github.com/SymbiFlow/yosys/pull/80

**Comment by litghost** [comment]
Yep, PR opened to fix it.

**Comment by sylv-io** [comment]
great thanks :+1:
