### ISSUE TITLE
XDC plugin missing annotations

### ISSUE THREAD

**Issue by mkurc-ant** [SymbiFlow/yosys-symbiflow-plugins#3]
The XDC plugins fails to annotate I/O bufs if they are not connected directly to the top-level port. For example, for design like that the annotation works fine:
```
module top (output wire top_o);

OBUF buf (
.I(some_signal),
.O(top_o)
);

...

endmodule
```

But for this one it does not provided that the `intermediate_wire` doesn't get optimized by Yosys:
```
module top (output wire top_o);

wire intermediate_wire;
assign top_o = intermediate_wire;

OBUF buf (
.I(some_signal),
.O(intermediate_wire)
);

...

endmodule
```

The XDC plugin should traverse from the top-level port down (or up) to any cell and annotate it if it is an IO buffer. Right now it considers only direct connections.

**Comment by tmichalak** [comment]
Solved with #4
