### ISSUE TITLE
PACKAGE_PINs constraint is not correctly parsed

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/yosys-symbiflow-plugins#31]
When LOCing a port to a specific PAD, the XDC can have to different forms

1. `set_property LOC A1 [get_ports {port}]`
2. `set_property PACKAGE_PIN A1 [get_ports {port}]`

Case 1 is handled, while case 2 is missing, causing the `port` to remain unconstrained.

**Comment by tmichalak** [comment]
Fixed in #34. Closing.
